#!/usr/bin/env bash
# build-index.sh — regenerate index.md from YAML frontmatter.
#
# Walks every .md file tracked by git (plus CURRENT_STATE.md / index.md even
# if untracked), extracts the YAML frontmatter, and writes index.md with a
# row per file: path, name, description, type, updated.
#
# Files without frontmatter are listed under "Unindexed" — a visible reminder
# that every context-repo file should declare its purpose.
#
# Usage:   scripts/build-index.sh
# Output:  index.md at repo root
#
# No dependencies beyond bash + awk. Safe to run in any environment.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

OUT="index.md"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# Collect all markdown files: tracked + untracked-but-not-ignored. Excludes
# index.md itself (no self-reference) and .git internals. Uses `git ls-files`
# with -co --exclude-standard so new-but-not-yet-committed files still show up
# on their first build — otherwise you add a file, run build-index, and the
# file is missing from its own index until after the next commit.
mapfile -t FILES < <(
  git ls-files -co --exclude-standard '*.md' 2>/dev/null \
    | sort -u \
    | grep -v '^index\.md$' \
    || true
)

extract_field() {
  # extract_field <file> <field>
  # Prints the value of <field> from the YAML frontmatter, or empty if missing.
  local file="$1" field="$2"
  awk -v f="$field" '
    BEGIN { in_fm = 0; n = 0 }
    /^---[[:space:]]*$/ {
      n++
      if (n == 1) { in_fm = 1; next }
      if (n == 2) { exit }
    }
    in_fm {
      if (match($0, "^[[:space:]]*" f "[[:space:]]*:[[:space:]]*")) {
        val = substr($0, RLENGTH + 1)
        sub(/[[:space:]]+$/, "", val)
        gsub(/^"|"$/, "", val)
        print val
        exit
      }
    }
  ' "$file"
}

has_frontmatter() {
  # has_frontmatter <file>
  # Returns 0 if file begins with --- and has a closing ---.
  local file="$1"
  head -1 "$file" | grep -q '^---[[:space:]]*$' || return 1
  awk 'NR == 1 { next } /^---[[:space:]]*$/ { print NR; exit }' "$file" | grep -q .
}

INDEXED=""
UNINDEXED=""

for f in "${FILES[@]}"; do
  [[ -f "$f" ]] || continue
  if has_frontmatter "$f"; then
    name=$(extract_field "$f" name)
    desc=$(extract_field "$f" description)
    type=$(extract_field "$f" type)
    updated=$(extract_field "$f" updated)
    INDEXED+="| [\`$f\`]($f) | ${name:-—} | ${desc:-—} | ${type:-—} | ${updated:-—} |"$'\n'
  else
    UNINDEXED+="- \`$f\` (no frontmatter — add one)"$'\n'
  fi
done

{
  cat <<EOF
---
name: index
description: Auto-generated index of every frontmatter-bearing file in this repo
type: index
updated: $(date -u +%Y-%m-%d)
---

# Index

Auto-generated by \`scripts/build-index.sh\`. Do not hand-edit — rerun the script
after any file add, remove, or retitle.

## Indexed

| Path | Name | Description | Type | Updated |
|---|---|---|---|---|
EOF
  printf '%s' "$INDEXED"

  if [[ -n "$UNINDEXED" ]]; then
    cat <<EOF

## Unindexed (frontmatter missing)

Every context-repo file should carry frontmatter per the spec §Required mechanics.
The files below do not and should be fixed.

EOF
    printf '%s' "$UNINDEXED"
  fi
} > "$TMP"

mv "$TMP" "$OUT"
trap - EXIT

echo "build-index.sh: wrote $OUT (${#FILES[@]} file(s) scanned)"
